### Machine Learning Bootcamp

Exercise file for Numpy

In [1]:
import numpy as np

In [2]:
my_list=[1,2,4,5,6]

In [3]:
my_list

[1, 2, 4, 5, 6]

In [4]:
np.array(my_list)

array([1, 2, 4, 5, 6])

In [5]:
myOneDarray=np.array(my_list)

In [6]:
myOneDarray

array([1, 2, 4, 5, 6])

In [7]:
mymultilist = [[1,2,3,4],[6,7,8,9],[7,8,9,0]]

In [8]:
mymultilist

[[1, 2, 3, 4], [6, 7, 8, 9], [7, 8, 9, 0]]

In [9]:
mytwoDarray=np.array(mymultilist)

In [10]:
mytwoDarray

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [7, 8, 9, 0]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [13]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Question: get a matrix of all 1s" it should be matrix of 3,4

In [14]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5,5)

array([[0.70364077, 0.59324881, 0.68882561, 0.74089082, 0.08338323],
       [0.09431033, 0.17335019, 0.46404281, 0.04129607, 0.67638697],
       [0.6480947 , 0.86229503, 0.18277387, 0.60920784, 0.07033924],
       [0.52237023, 0.31948889, 0.79812484, 0.27865272, 0.2509711 ],
       [0.27657992, 0.54987956, 0.56958392, 0.13451915, 0.78159564]])

In [17]:
np.random.randn(5)

array([ 0.13996312,  0.06084941, -0.35591642, -0.13943667,  1.04596579])

In [18]:
np.random.randint(1,77)

19

In [19]:
mynum = np.arange(25)

In [20]:
mynum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
myreshaped = mynum.reshape(5,5)

In [22]:
myreshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
myreshaped.max()

24

In [24]:
myreshaped.dtype

dtype('int64')