## intermediate numpy

In [1]:
import numpy as np

In [3]:
myarray = np.arange(10,21)

In [4]:
myarray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
myarray[0]

10

In [8]:
myarray[2:3]

array([12])

In [9]:
myarray[ :4]

array([10, 11, 12, 13])

In [10]:
myarray[4:]

array([14, 15, 16, 17, 18, 19, 20])

In [11]:
partarray = myarray[ :4]

In [12]:
partarray

array([10, 11, 12, 13])

In [13]:
partarray[ :]=25

In [14]:
partarray

array([25, 25, 25, 25])

In [15]:
copyarray = myarray.copy()

In [16]:
copyarray

array([25, 25, 25, 25, 14, 15, 16, 17, 18, 19, 20])

In [17]:
copyarray[:]= 200

In [18]:
copyarray

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [19]:
myarray

array([25, 25, 25, 25, 14, 15, 16, 17, 18, 19, 20])