## intermediate numpy

In [1]:
import numpy as np

In [3]:
myarray = np.arange(10,21)

In [4]:
myarray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
myarray[0]

10

In [8]:
myarray[2:3]

array([12])

In [9]:
myarray[ :4]

array([10, 11, 12, 13])

In [10]:
myarray[4:]

array([14, 15, 16, 17, 18, 19, 20])

In [11]:
partarray = myarray[ :4]

In [12]:
partarray

array([10, 11, 12, 13])

In [13]:
partarray[ :]=25

In [14]:
partarray

array([25, 25, 25, 25])

In [15]:
copyarray = myarray.copy()

In [16]:
copyarray

array([25, 25, 25, 25, 14, 15, 16, 17, 18, 19, 20])

In [17]:
copyarray[:]= 200

In [18]:
copyarray

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [19]:
myarray

array([25, 25, 25, 25, 14, 15, 16, 17, 18, 19, 20])

# 2D array

In [20]:
my2darray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
my2darray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#how to select a value form 2d array forexample grabe 8

In [26]:
my2darray[2][1]

8

In [27]:
my2darray[2,1]

8

In [29]:
my2darray[2]

array([7, 8, 9])

In [33]:
#grabing 2,3 and 5,6  submatrix

In [32]:
my2darray[ :2 ,1: ]

array([[2, 3],
       [5, 6]])

In [52]:
#NUmpy Conditional RETURN

In [53]:
newarray = np.arange(2,20)

In [54]:
newarray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [55]:
newarray[newarray >10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [56]:
newarray>10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [60]:
newarray 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [61]:
newarray*2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [65]:
np.sqrt(newarray)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])

In [71]:
#What are the advantages of using NUMPY library over standard Python lists?

In [67]:
#Write a NUMPY code to create a 3x3 matrix with values ranging from 1 to 9.

In [ ]:
#Explain the difference between broadcasting and vectorization in NUMPY.

In [ ]:
#Explain the difference between broadcasting and vectorization in NUMPY.

In [ ]:
#Write a NUMPY code to find the mean and standard deviation of a given array.

In [ ]:
#.Explain the purpose of the reshape() function in NUMPY with an example.

In [ ]:
#Discuss the usage of universal functions (ufuncs) in NUMPY with examples.

In [68]:
#What is the purpose of the np.random.rand() function in NUMPY?

In [69]:
#Write a code to perform matrix multiplication using NUMPY.

In [70]:
#Explain the concept of array indexing and slicing in NUMPY.